---
title: "Mini-Project 2"
author: "Anjali Desai, Prayasha Chaudhary, Ariana Meredith"
date: "March 24, 2017"
output: html_document
---

## Loading the data and Libraries 

```{r, include=FALSE}
library(ggmap)
library(maps)
library(mapdata)

load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")

library(tidyverse)
library(ggplot2)
library(dplyr)
```

 
## Sorting the data
```{r}

Cand <- candidates %>%
  select(cand_id, cand_name, cand_party_affiliation, cand_election_yr)  %>%
  filter( cand_election_yr == 2012) %>%
  arrange(cand_name)

House <- house_elections %>%
  select(fec_id, general_votes, state, candidate_name, party) 
  #filter(party == c("D", "R")) %>%
  #filter(state == c("ME" ,"NH" , "VT", "MA", "RI", "CT", "NY", "NJ", "PA"))
  #arrange(candidate_name)

x <- rename(Cand,  fec_id = cand_id)
joined <- x %>% inner_join(House,  by = "fec_id") %>%
  filter(cand_party_affiliation == "DEM" | cand_party_affiliation == "REP")
joined

```

## Creating the graph
```{r}
ggplot(data = joined, aes( x= state, y=general_votes, fill = cand_party_affiliation))+ geom_bar(stat = "identity")

```


```{r}
states <- map_data("state")
north_east <- subset(states, region %in% c("maine", "new hampshire", "vermont","massachusetts", "rhode island", "connecticut", "new york", "new jersey", "pennsylvania" ))
ditch_the_axes <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank()
  )

northEast <- ggplot(data= north_east) + geom_polygon( aes(x=long, y = lat, group= group ), color = "black")+coord_fixed(1.3)

#northEast + geom_polygon(data = joined, aes(fill = cand_party_affiliation), color = "white")+ geom_polygon(color = "black", fill = NA) +theme_bw() + ditch_the_axes
```

